server:
  port: 8083

spring:
  application:
    name: technical-advisor
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/technical_advisor
    password: spintechs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
