@startuml
actor Recruiter
actor TechnicalAdvisor
participant System

Recruiter -> System: Create new interview request
System --> Recruiter: Response of the request
System ->> System: Determination of eligible TechnicalAdvisor / X / Y

group Random selection of X TechnicalAdvisor
    System ->> TechnicalAdvisor: Send an email containing \n the "Accept" and "Reject" links
    ref over System
        Asynchrone Job
    end ref
end

@enduml