@startuml

actor RecruiterActor
actor TechnicalAdvisorActor
participant InterviewRequest
participant TechnicalAdvisor
participant MessageQueue
participant Notification
participant Recruiter
participant Interview

TechnicalAdvisorActor -> InterviewRequest: Click on the link reject Interview
InterviewRequest --> TechnicalAdvisorActor: Response of the request
group Check Rejected Request
    alt If X TechnicalAdvisor has rejected the request
        alt If there are more of TechnicalAdvisor eligible for the request
            ref over InterviewRequest
                Run Iteration Of Process
            end ref
        else
            InterviewRequest ->> MessageQueue: Produce Message No Availible TechnicalAdvisor
            Interview <<- MessageQueue: Consume Message No Availible TechnicalAdvisor
            Interview ->> Interview: Set Status Of The Interview
            Notification <<- MessageQueue: Consume Message No Availible TechnicalAdvisor
            Notification ->> Recruiter: Get Recruiter Detail
            Recruiter --> Notification: Return Recruiter Detail
            Notification ->> RecruiterActor: Send email all the TechnicalAdvisor eligible refused the request
        end
    end
end
@enduml