@startuml
actor RecruiterActor
actor TechnicalAdvisorActor1
actor TechnicalAdvisorActor2
participant InterviewRequest
participant MessageQueue
participant Notification
participant TechnicalAdvisor
participant Recruiter

TechnicalAdvisorActor1 -> InterviewRequest: Click on the link confirme reject Interview
InterviewRequest --> TechnicalAdvisorActor1: Response of the request
alt If this TechnicalAdvisor1 is the first one accept the request (Old StatusOfRequest Assigned)
    alt If there is another TechnicalAdvisor2 accept this request
        InterviewRequest ->> MessageQueue: Produce Message Accepted Interview Request
        Notification <<- MessageQueue: Consume Message Accepted Interview Request
        Notification ->> Recruiter: Get Recruiter Detail
        Recruiter --> Notification: Return Recruiter Detail
        Notification ->> RecruiterActor: Send an email containing a link to details of the TechnicalAdvisor who accept
        Notification ->> TechnicalAdvisor: Get TechnicalAdvisor Detail
        TechnicalAdvisor --> Notification: Return TechnicalAdvisor Detail
        Notification ->> TechnicalAdvisorActor2: Send an email to the next TechnicalAdvisor \n the interview request is assigned \n send the recruiter's informations
    else
        ref over InterviewRequest
            Check Rejected Request
        end ref
    end
else (Old StatusOfRequest Accepted)
    ref over InterviewRequest
        Check Rejected Request
    end ref
end

@enduml