@startuml
actor RecruiterActor
participant InterviewRequest

RecruiterActor -> InterviewRequest: Decline the acceptance of Interview Request
System --> RecruiterActor: Response of the request
ref over InterviewRequest
    Choise the Request
end ref

@enduml