@startuml
actor RecruiterActor
participant InterviewRequest

group Choise the Request
    RecruiterActor -> InterviewRequest: Choise the accepted Request
    InterviewRequest -> RecruiterActor: Response of the Request
end ref

@enduml