server:
  port: 8082
spring:
  application:
    name: interview-request
  datasource:
    username: test
    url: jdbc:postgresql://localhost:5432/interview_request
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: interviewRequestId
      value-deserializer: ca.levio.interviewrequest.queue.GenerateInterviewRequestDtoDeserializer
      properties.spring.json.trusted.packages: "*"
