@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
' uncomment the following line and comment the first to use locally
' !include C4_Deployment.puml

AddElementTag("fallback", $bgColor="#c0c0c0")
AddRelTag("fallback", $textColor="#c0c0c0", $lineColor="#438DD5")

' calculated legend is used (activated in last line)
' LAYOUT_WITH_LEGEND()

title Deployment diagram for Interview Management System - API Application

Deployment_Node(plc, "Big Bank plc", "Big Bank plc data center"){
    Deployment_Node(dn, "bigbank-api***\tx8"){
        Deployment_Node(nginx, "NGINX", "NGINX"){
            Container(spa, "API Application", "Java and Spring MVC", "Provides Interview Management functionality via a JSON/HTTPS API.")
        }
    }
    Deployment_Node(dn, "bigbank-api***\tx8"){
        Deployment_Node(apache, "Apache Tomcat", "Apache Tomcat 8.x"){
            Container(api, "API Application", "Java and Spring MVC", "Provides Interview Management functionality via a JSON/HTTPS API.")
        }
    }
    Deployment_Node(bigbankdb01, "bigbank-db01"){
        Deployment_Node(postgres, "Postgres - Primary", "Postgres"){
            ContainerDb(db1, "Database", "Relational Database Schema", "Stores All Data.")
        }
    }
    Deployment_Node(bigbankdb02, "bigbank-db02", "Ubuntu 16.04 LTS", $tags="fallback") {
        Deployment_Node(postgres, "Postgres - Secondary", "Postgres", $tags="fallback") {
            ContainerDb(db2, "Database", "Relational Database Schema", "Stores All Data.", $tags="fallback")
        }
    }
}

Deployment_Node(mob, "Mobile device", "Apple IOS or Android"){
    Container(mobile, "Mobile App", "Xamarin", "Provides a limited subset of the Interview Management functionality to customers via their mobile device.")
}

Deployment_Node(computer, "Computer", "Microsoft Windows or Apple macOS"){
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Apple Safari or Microsoft Edge ..."){
        Container(web, "Single Page Application", "JavaScript and Angular", "Provides all of the Interview Management functionality to customers via their web browser.")
    }
}

Rel(mobile, api, "Makes API calls to", "json/HTTPS")
Rel(spa, api, "Makes API calls to", "json/HTTPS")
Rel_U(web, spa, "Delivers to the web browser")
Rel(api, db1, "Reads from and writes to", "JDBC")
Rel(api, db2, "Reads from and writes to", "JDBC", $tags="fallback")
Rel_R(db1, db2, "Replicates data to")

@enduml